import { PRODUCTS_BY_ID } from './catalog.js';

// Quantités exprimées pour UNE portion, dans l'unité du produit du catalogue (g, ml ou pièce).

export const CATEGORIES = Object.freeze({
  MEAT: 'viande',
  FISH: 'poisson',
  VEGETARIAN: 'vegetarien',
});

export const MEAL_TYPES = Object.freeze({
  MAIN: 'plat',
  BREAKFAST: 'petit-dejeuner',
  SNACK: 'collation',
});

// Une recette rapide doit aussi rester courte : au-delà de 6 ingrédients frais, elle demande
// trop de découpe. Les basiques du placard (huile, épices) ne comptent pas.
export const MAX_FRESH_INGREDIENTS_WHEN_TIME_LIMITED = 6;

export const CATEGORY_LABELS = Object.freeze({
  [CATEGORIES.MEAT]: 'Viande',
  [CATEGORIES.FISH]: 'Poisson',
  [CATEGORIES.VEGETARIAN]: 'Végétarien',
});

function defineRecipe({ id, name, category, mealType = MEAL_TYPES.MAIN, containsPork = false, prepMinutes, ingredients, steps }) {
  return Object.freeze({
    id,
    name,
    category,
    mealType,
    containsPork,
    prepMinutes,
    ingredients: Object.freeze({ ...ingredients }),
    steps: Object.freeze([...steps]),
  });
}

export const RECIPES = Object.freeze([
  defineRecipe({
    id: 'spaghetti-bolognaise',
    name: 'Spaghetti bolognaise',
    category: CATEGORIES.MEAT,
    prepMinutes: 35,
    ingredients: { spaghetti: 100, 'boeuf-hache': 100, 'tomates-concassees': 150, oignon: 40, carotte: 40, ail: 3, 'huile-olive': 5, herbes: 1 },
    steps: [
      "Faire revenir l'oignon, l'ail et la carotte hachés dans l'huile.",
      'Ajouter le bœuf, le faire dorer puis verser les tomates et les herbes. Laisser mijoter 20 min.',
      'Cuire les spaghetti, égoutter et servir nappés de sauce.',
    ],
  }),
  defineRecipe({
    id: 'poulet-curry-coco',
    name: 'Poulet au curry et lait de coco, riz basmati',
    category: CATEGORIES.MEAT,
    prepMinutes: 30,
    ingredients: { 'poulet-filet': 125, 'lait-coco': 100, riz: 75, oignon: 40, poivron: 0.5, curry: 2, 'huile-olive': 5 },
    steps: [
      "Émincer l'oignon et le poivron, les faire revenir avec le curry.",
      'Ajouter le poulet en dés, dorer 5 min puis verser le lait de coco. Mijoter 15 min.',
      'Servir avec le riz cuit.',
    ],
  }),
  defineRecipe({
    id: 'chili-con-carne',
    name: 'Chili con carne',
    category: CATEGORIES.MEAT,
    prepMinutes: 40,
    ingredients: { 'boeuf-hache': 100, 'haricots-rouges': 80, 'tomates-concassees': 150, oignon: 40, poivron: 0.33, cumin: 1, paprika: 1, riz: 70, 'huile-olive': 5 },
    steps: [
      "Faire revenir l'oignon et le poivron, ajouter le bœuf et les épices.",
      'Verser les tomates et les haricots rincés, mijoter 25 min.',
      'Servir avec le riz.',
    ],
  }),
  defineRecipe({
    id: 'quiche-lorraine',
    name: 'Quiche lorraine et salade verte',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 45,
    ingredients: { 'pate-brisee': 0.25, lardons: 50, oeuf: 1, 'creme-epaisse': 40, lait: 50, emmental: 25, salade: 0.25 },
    steps: [
      'Préchauffer le four à 200 °C et foncer un moule avec la pâte.',
      "Faire griller les lardons à sec, les répartir sur la pâte avec l'emmental.",
      'Battre œufs, crème et lait, verser et cuire 35 min. Servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'carbonara',
    name: 'Spaghetti carbonara',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { spaghetti: 100, lardons: 60, oeuf: 1, parmesan: 20, poivre: 0.5 },
    steps: [
      'Cuire les spaghetti. Pendant ce temps, dorer les lardons à sec.',
      'Battre les œufs avec le fromage râpé et beaucoup de poivre.',
      'Hors du feu, mélanger pâtes, lardons et œufs avec une louche d’eau de cuisson.',
    ],
  }),
  defineRecipe({
    id: 'fajitas-poulet',
    name: 'Fajitas de poulet aux poivrons',
    category: CATEGORIES.MEAT,
    prepMinutes: 25,
    ingredients: { tortilla: 2, 'poulet-filet': 110, poivron: 0.5, oignon: 40, paprika: 1, 'creme-epaisse': 30, salade: 0.15, 'huile-olive': 5 },
    steps: [
      'Émincer poulet, poivron et oignon. Saisir le tout avec le paprika 10 min.',
      'Réchauffer les tortillas à la poêle.',
      'Garnir de poulet, salade et une cuillère de crème.',
    ],
  }),
  defineRecipe({
    id: 'saucisses-puree',
    name: 'Saucisses de Toulouse, purée et haricots verts',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 35,
    ingredients: { saucisse: 150, 'pomme-de-terre': 250, lait: 60, beurre: 10, 'haricots-verts': 150 },
    steps: [
      'Cuire les pommes de terre épluchées 20 min dans l’eau salée.',
      'Dorer les saucisses à la poêle 15 min en les retournant.',
      'Écraser les pommes de terre avec le lait chaud et le beurre. Cuire les haricots verts 8 min.',
    ],
  }),
  defineRecipe({
    id: 'hachis-parmentier',
    name: 'Hachis parmentier',
    category: CATEGORIES.MEAT,
    prepMinutes: 50,
    ingredients: { 'boeuf-hache': 100, 'pomme-de-terre': 250, lait: 60, beurre: 10, oignon: 40, emmental: 25, 'huile-olive': 5 },
    steps: [
      "Cuire les pommes de terre et préparer une purée avec le lait et le beurre.",
      "Faire revenir l'oignon puis le bœuf haché.",
      'Monter en couches dans un plat, parsemer d’emmental et gratiner 20 min à 200 °C.',
    ],
  }),
  defineRecipe({
    id: 'gnocchi-champignons-jambon',
    name: 'Gnocchi crème, champignons et jambon',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { gnocchi: 200, champignon: 100, 'creme-epaisse': 50, jambon: 40, parmesan: 10, 'huile-olive': 5 },
    steps: [
      'Dorer les gnocchi à la poêle avec un filet d’huile, réserver.',
      'Faire sauter les champignons émincés, ajouter le jambon en lanières et la crème.',
      'Remettre les gnocchi, mélanger et parsemer de fromage.',
    ],
  }),
  defineRecipe({
    id: 'cuisses-poulet-patates-douces',
    name: 'Cuisses de poulet rôties, patates douces au four',
    category: CATEGORIES.MEAT,
    prepMinutes: 55,
    ingredients: { 'cuisse-poulet': 250, 'patate-douce': 200, herbes: 1, 'huile-olive': 10, salade: 0.25 },
    steps: [
      'Préchauffer le four à 210 °C. Couper les patates douces en quartiers.',
      "Disposer poulet et patates dans un plat, arroser d'huile et d'herbes.",
      'Rôtir 45 min en retournant à mi-cuisson. Servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'poelee-chorizo',
    name: 'Poêlée de pommes de terre, chorizo et poivrons',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 30,
    ingredients: { chorizo: 50, 'pomme-de-terre': 250, poivron: 0.5, oignon: 40, paprika: 1, 'huile-olive': 10 },
    steps: [
      'Couper les pommes de terre en dés et les faire dorer 15 min dans l’huile.',
      "Ajouter l'oignon, le poivron et le chorizo en rondelles.",
      'Assaisonner au paprika et poursuivre 10 min à feu moyen.',
    ],
  }),

  defineRecipe({
    id: 'saumon-riz-brocoli',
    name: 'Saumon au citron, riz et brocoli',
    category: CATEGORIES.FISH,
    prepMinutes: 25,
    ingredients: { saumon: 125, riz: 75, brocoli: 0.4, citron: 0.25, 'huile-olive': 5 },
    steps: [
      'Cuire le riz. Cuire le brocoli en fleurettes 6 min à la vapeur.',
      'Saisir le saumon 4 min côté peau puis 2 min de l’autre côté.',
      'Arroser de jus de citron au moment de servir.',
    ],
  }),
  defineRecipe({
    id: 'colin-epinards-puree',
    name: 'Colin à la crème, épinards et purée',
    category: CATEGORIES.FISH,
    prepMinutes: 35,
    ingredients: { colin: 130, epinards: 150, 'creme-epaisse': 40, 'pomme-de-terre': 250, lait: 60, beurre: 10, citron: 0.2 },
    steps: [
      'Préparer une purée avec les pommes de terre, le lait et le beurre.',
      'Faire fondre les épinards à la poêle, ajouter la crème.',
      'Cuire le colin 10 min au four à 200 °C avec un filet de citron.',
    ],
  }),
  defineRecipe({
    id: 'nouilles-crevettes',
    name: 'Nouilles sautées aux crevettes',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { nouilles: 80, crevettes: 70, carotte: 60, poivron: 0.33, oeuf: 0.5, 'sauce-soja': 15, 'huile-olive': 5, ail: 2 },
    steps: [
      'Cuire les nouilles 4 min, égoutter.',
      "Faire sauter l'ail, la carotte en julienne et le poivron 5 min à feu vif.",
      'Ajouter les crevettes, l’œuf battu, les nouilles et la sauce soja. Mélanger 2 min.',
    ],
  }),
  defineRecipe({
    id: 'spaghetti-thon-tomate',
    name: 'Spaghetti au thon et à la tomate',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { spaghetti: 100, thon: 60, coulis: 125, oignon: 30, herbes: 1, 'huile-olive': 5 },
    steps: [
      "Faire revenir l'oignon, ajouter le coulis et les herbes, mijoter 10 min.",
      'Ajouter le thon émietté hors du feu.',
      'Mélanger avec les spaghetti cuits.',
    ],
  }),

  defineRecipe({
    id: 'dahl-lentilles',
    name: 'Dahl de lentilles corail',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 30,
    ingredients: { 'lentilles-corail': 80, 'lait-coco': 80, 'tomates-concassees': 100, oignon: 40, ail: 3, curry: 2, riz: 60, citron: 0.25 },
    steps: [
      "Faire revenir l'oignon, l'ail et le curry.",
      'Ajouter lentilles rincées, tomates, lait de coco et 150 ml d’eau par personne. Cuire 20 min.',
      'Servir sur le riz avec un filet de citron.',
    ],
  }),
  defineRecipe({
    id: 'chili-sin-carne',
    name: 'Chili sin carne',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 35,
    ingredients: { 'haricots-rouges': 120, mais: 60, 'tomates-concassees': 150, poivron: 0.5, oignon: 40, cumin: 1, paprika: 1, riz: 70, 'huile-olive': 5 },
    steps: [
      "Faire revenir l'oignon et le poivron avec les épices.",
      'Ajouter tomates, haricots et maïs égouttés. Mijoter 20 min.',
      'Servir avec le riz.',
    ],
  }),
  defineRecipe({
    id: 'quiche-poireaux-chevre',
    name: 'Quiche poireaux et chèvre',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 50,
    ingredients: { 'pate-brisee': 0.25, poireau: 120, chevre: 40, oeuf: 1, 'creme-epaisse': 50, salade: 0.25, beurre: 5 },
    steps: [
      'Faire fondre les poireaux émincés au beurre 15 min.',
      'Garnir la pâte de poireaux et de rondelles de chèvre.',
      'Verser œufs battus et crème, cuire 35 min à 200 °C. Servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'penne-pesto-courgettes',
    name: 'Penne au pesto, courgettes et mozzarella',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { penne: 100, pesto: 40, courgette: 150, mozzarella: 60, parmesan: 10, 'huile-olive': 5 },
    steps: [
      'Faire sauter les courgettes en demi-rondelles 8 min.',
      'Cuire les penne, les mélanger au pesto et aux courgettes.',
      'Ajouter la mozzarella en morceaux et le fromage râpé.',
    ],
  }),
  defineRecipe({
    id: 'tortilla-espagnole',
    name: 'Tortilla espagnole aux champignons',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 35,
    ingredients: { oeuf: 2, 'pomme-de-terre': 200, oignon: 50, champignon: 60, salade: 0.25, 'huile-olive': 10 },
    steps: [
      "Cuire doucement pommes de terre en fines tranches et oignon dans l'huile 15 min.",
      'Ajouter les champignons, puis les œufs battus.',
      'Cuire à couvert 10 min à feu doux, retourner à l’aide d’une assiette. Servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'couscous-legumes',
    name: 'Couscous de légumes et pois chiches',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 40,
    ingredients: { semoule: 80, 'pois-chiches': 100, carotte: 80, courgette: 100, oignon: 40, 'tomates-concassees': 80, cumin: 1, bouillon: 0.5, 'huile-olive': 5 },
    steps: [
      "Faire revenir l'oignon, ajouter carottes et courgettes en tronçons, tomates, cumin et bouillon.",
      'Couvrir d’eau et mijoter 25 min, ajouter les pois chiches les 5 dernières minutes.',
      'Gonfler la semoule dans son volume d’eau bouillante et servir.',
    ],
  }),
  defineRecipe({
    id: 'wok-tofu',
    name: 'Wok de tofu, brocoli et nouilles',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 25,
    ingredients: { tofu: 100, nouilles: 80, brocoli: 0.3, carotte: 60, 'sauce-soja': 15, ail: 2, 'huile-olive': 10 },
    steps: [
      'Dorer le tofu en cubes dans l’huile, réserver.',
      "Faire sauter l'ail, le brocoli et la carotte 6 min.",
      'Ajouter les nouilles cuites, le tofu et la sauce soja.',
    ],
  }),
  defineRecipe({
    id: 'veloute-lentilles-carottes',
    name: 'Velouté de lentilles vertes et carottes',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 40,
    ingredients: { 'lentilles-vertes': 70, carotte: 100, oignon: 40, bouillon: 0.5, 'creme-epaisse': 20, cumin: 1, 'huile-olive': 5 },
    steps: [
      "Faire revenir l'oignon et les carottes en rondelles.",
      'Ajouter lentilles, cumin, bouillon et 350 ml d’eau par personne. Cuire 30 min.',
      'Mixer et servir avec une cuillère de crème.',
    ],
  }),
  defineRecipe({
    id: 'feuillete-epinards-feta',
    name: 'Feuilleté épinards et feta',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 40,
    ingredients: { 'pate-feuilletee': 0.25, epinards: 150, feta: 50, oeuf: 0.5, salade: 0.25 },
    steps: [
      'Faire fondre les épinards et bien les égoutter.',
      "Mélanger avec la feta émiettée et l'œuf battu.",
      'Garnir la pâte, replier en chausson et cuire 25 min à 200 °C.',
    ],
  }),
  defineRecipe({
    id: 'curry-pois-chiches',
    name: 'Curry de pois chiches aux épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 25,
    ingredients: { 'pois-chiches': 130, epinards: 100, 'lait-coco': 80, 'tomates-concassees': 80, curry: 2, oignon: 40, riz: 70 },
    steps: [
      "Faire revenir l'oignon avec le curry.",
      'Ajouter tomates, lait de coco, pois chiches et épinards. Mijoter 15 min.',
      'Servir avec le riz.',
    ],
  }),
  defineRecipe({
    id: 'ratatouille-oeuf',
    name: 'Ratatouille, semoule et œuf au plat',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 45,
    ingredients: { courgette: 120, aubergine: 0.4, poivron: 0.4, tomate: 120, oignon: 40, ail: 3, herbes: 1, oeuf: 1, semoule: 60, 'huile-olive': 10 },
    steps: [
      "Couper tous les légumes en dés et les faire revenir dans l'huile avec l'ail.",
      'Ajouter les herbes, couvrir et mijoter 30 min.',
      'Servir avec la semoule et un œuf au plat.',
    ],
  }),
  defineRecipe({
    id: 'gnocchi-tomate-mozzarella',
    name: 'Gnocchi gratinés tomate et mozzarella',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 25,
    ingredients: { gnocchi: 200, coulis: 100, mozzarella: 60, herbes: 1, salade: 0.2 },
    steps: [
      'Mélanger les gnocchi crus avec le coulis et les herbes dans un plat.',
      'Couvrir de mozzarella en tranches.',
      'Enfourner 20 min à 210 °C. Servir avec la salade.',
    ],
  }),

  // Recettes légères et riches en protéines : elles rassasient sous 500 kcal environ.
  defineRecipe({
    id: 'poulet-haricots-verts',
    name: 'Poulet aux herbes, haricots verts et pommes de terre vapeur',
    category: CATEGORIES.MEAT,
    prepMinutes: 25,
    ingredients: { 'poulet-filet': 150, 'haricots-verts': 200, 'pomme-de-terre': 200, 'huile-olive': 5, herbes: 1 },
    steps: [
      'Cuire les pommes de terre en morceaux 15 min à la vapeur ou dans l’eau.',
      'Cuire les haricots verts 8 min.',
      'Saisir le poulet avec l’huile et les herbes, 6 min par face.',
    ],
  }),
  defineRecipe({
    id: 'keftas-courgettes-semoule',
    name: 'Boulettes de bœuf au cumin, courgettes et semoule',
    category: CATEGORIES.MEAT,
    prepMinutes: 30,
    ingredients: { 'boeuf-hache': 120, courgette: 200, semoule: 50, 'tomates-concassees': 100, oignon: 30, cumin: 1, 'huile-olive': 5 },
    steps: [
      'Mélanger le bœuf avec le cumin et la moitié de l’oignon haché, former des boulettes.',
      'Les dorer, ajouter le reste de l’oignon, les courgettes en dés et les tomates. Mijoter 15 min.',
      'Servir avec la semoule gonflée à l’eau bouillante.',
    ],
  }),
  defineRecipe({
    id: 'colin-papillote-poireaux',
    name: 'Colin en papillote, poireaux, carottes et riz',
    category: CATEGORIES.FISH,
    prepMinutes: 30,
    ingredients: { colin: 150, poireau: 150, carotte: 100, citron: 0.25, riz: 50, 'huile-olive': 5 },
    steps: [
      'Préchauffer le four à 200 °C. Émincer finement poireaux et carottes.',
      'Déposer légumes et colin sur du papier cuisson, arroser de citron et d’huile, fermer.',
      'Cuire 20 min. Servir avec le riz.',
    ],
  }),
  defineRecipe({
    id: 'crevettes-courgettes-ail',
    name: 'Crevettes à l’ail, courgettes et riz',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { crevettes: 120, courgette: 200, riz: 50, ail: 3, citron: 0.25, 'huile-olive': 5 },
    steps: [
      'Cuire le riz.',
      "Faire sauter les courgettes en demi-rondelles 6 min avec l'ail.",
      'Ajouter les crevettes 2 min et le jus de citron.',
    ],
  }),
  defineRecipe({
    id: 'omelette-champignons-epinards',
    name: 'Omelette champignons et épinards, salade verte',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { oeuf: 3, champignon: 100, epinards: 100, emmental: 15, salade: 0.25, 'huile-olive': 5 },
    steps: [
      'Faire sauter les champignons émincés puis les épinards jusqu’à évaporation.',
      'Verser les œufs battus, parsemer d’emmental.',
      'Cuire à feu doux 4 min, plier et servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'soupe-poireaux-oeufs',
    name: 'Soupe poireaux-carottes et œufs mollets',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 35,
    ingredients: { poireau: 150, carotte: 100, 'pomme-de-terre': 100, bouillon: 0.5, oeuf: 2 },
    steps: [
      'Couper les légumes, les couvrir d’eau avec le bouillon, cuire 25 min puis mixer.',
      'Cuire les œufs 6 min dans l’eau bouillante, les écaler.',
      'Servir la soupe avec les œufs mollets.',
    ],
  }),
  defineRecipe({
    id: 'tofu-brocoli-riz',
    name: 'Tofu sauté au soja, brocoli et riz',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 25,
    ingredients: { tofu: 150, brocoli: 0.4, riz: 50, 'sauce-soja': 15, ail: 2, 'huile-olive': 5 },
    steps: [
      'Cuire le riz. Cuire le brocoli en fleurettes 5 min à la vapeur.',
      "Dorer le tofu en cubes avec l'ail.",
      'Ajouter le brocoli et la sauce soja, mélanger 2 min.',
    ],
  }),

  defineRecipe({
    id: 'poelee-pois-chiches-oeuf',
    name: 'Poêlée de pois chiches, épinards et œuf',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { 'pois-chiches': 130, epinards: 150, oeuf: 1, semoule: 40, ail: 2, cumin: 1, 'huile-olive': 5 },
    steps: [
      'Gonfler la semoule dans son volume d’eau bouillante.',
      "Faire revenir l'ail, les pois chiches égouttés et le cumin 3 min, ajouter les épinards jusqu’à ce qu’ils fondent.",
      'Casser l’œuf au milieu, couvrir 4 min et servir sur la semoule.',
    ],
  }),
  defineRecipe({
    id: 'riz-saute-oeufs',
    name: 'Riz sauté aux œufs et légumes',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { riz: 60, oeuf: 2, carotte: 60, poivron: 0.33, 'sauce-soja': 10, 'huile-olive': 5 },
    steps: [
      'Cuire le riz (ou utiliser un reste de riz froid).',
      'Faire sauter la carotte râpée et le poivron en dés 4 min.',
      'Ajouter le riz, pousser sur le côté, brouiller les œufs puis mélanger avec la sauce soja.',
    ],
  }),

  // Recettes express (20 min maximum), choisies pour leur petit prix et leurs ingrédients communs.
  defineRecipe({
    id: 'penne-courgettes-oeuf',
    name: 'Penne aux courgettes, œuf et grana padano',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { penne: 80, courgette: 150, oeuf: 1, parmesan: 15, ail: 2, 'huile-olive': 5 },
    steps: [
      'Cuire les penne.',
      "Faire sauter les courgettes râpées et l'ail 5 min.",
      'Hors du feu, mélanger pâtes, courgettes, œuf battu et fromage.',
    ],
  }),
  defineRecipe({
    id: 'soupe-lentilles-corail-coco',
    name: 'Soupe de lentilles corail, carotte et coco',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { 'lentilles-corail': 60, 'lait-coco': 50, carotte: 100, oignon: 30, curry: 1, bouillon: 0.5 },
    steps: [
      "Faire revenir l'oignon et la carotte en rondelles 2 min avec le curry.",
      'Ajouter les lentilles, le bouillon et 350 ml d’eau. Cuire 15 min.',
      'Ajouter le lait de coco et mixer.',
    ],
  }),
  defineRecipe({
    id: 'poulet-champignons-riz',
    name: 'Poulet aux champignons à la crème, riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 110, champignon: 120, riz: 60, 'creme-epaisse': 20, 'huile-olive': 5 },
    steps: [
      'Cuire le riz.',
      'Dorer le poulet en lanières 5 min, ajouter les champignons émincés 5 min.',
      'Ajouter la crème, laisser réduire 2 min.',
    ],
  }),
  defineRecipe({
    id: 'boeuf-courgettes-riz',
    name: 'Bœuf haché sauté aux courgettes et riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'boeuf-hache': 110, courgette: 150, riz: 60, oignon: 30, 'sauce-soja': 10, 'huile-olive': 5 },
    steps: [
      'Cuire le riz.',
      "Faire revenir l'oignon et le bœuf 5 min, ajouter les courgettes en dés 7 min.",
      'Assaisonner à la sauce soja et servir sur le riz.',
    ],
  }),
  defineRecipe({
    id: 'quesadillas-haricots',
    name: 'Quesadillas haricots rouges et fromage',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { tortilla: 2, 'haricots-rouges': 80, emmental: 25, poivron: 0.33, salade: 0.15, cumin: 1 },
    steps: [
      'Écraser les haricots avec le cumin, ajouter le poivron en petits dés.',
      'Étaler sur une tortilla, parsemer de fromage, couvrir de la seconde.',
      'Dorer 3 min par face à la poêle, couper en parts, servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'shakshuka-express',
    name: 'Œufs pochés à la tomate et au poivron, pain complet',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { 'tomates-concassees': 200, oeuf: 2, oignon: 40, poivron: 0.33, 'pain-complet': 50, cumin: 1, 'huile-olive': 5 },
    steps: [
      "Faire revenir l'oignon et le poivron émincés 5 min avec le cumin.",
      'Ajouter les tomates, mijoter 5 min.',
      'Creuser deux puits, y casser les œufs, couvrir 6 min. Servir avec le pain.',
    ],
  }),
  defineRecipe({
    id: 'nouilles-poulet-carottes',
    name: 'Nouilles sautées au poulet et carottes',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { nouilles: 70, 'poulet-filet': 100, carotte: 80, oignon: 30, 'sauce-soja': 15, 'huile-olive': 5 },
    steps: [
      'Cuire les nouilles 4 min, égoutter.',
      'Saisir le poulet en lanières, ajouter oignon et carotte râpée 5 min.',
      'Ajouter les nouilles et la sauce soja, mélanger 2 min.',
    ],
  }),
  defineRecipe({
    id: 'colin-riz-haricots-verts',
    name: 'Colin poêlé au citron, riz et haricots verts',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { colin: 150, riz: 60, 'haricots-verts': 150, citron: 0.25, 'huile-olive': 5 },
    steps: [
      'Cuire le riz et les haricots verts.',
      'Poêler le colin encore surgelé 6 min par face à couvert.',
      'Arroser de jus de citron.',
    ],
  }),
  defineRecipe({
    id: 'spaghetti-lentilles-tomate',
    name: 'Spaghetti sauce tomate aux lentilles corail',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { spaghetti: 80, 'lentilles-corail': 40, 'tomates-concassees': 150, oignon: 30, herbes: 1, 'huile-olive': 5 },
    steps: [
      "Faire revenir l'oignon, ajouter tomates, lentilles, herbes et 100 ml d’eau. Cuire 15 min.",
      'Pendant ce temps, cuire les spaghetti.',
      'Mélanger et servir.',
    ],
  }),
  defineRecipe({
    id: 'curry-poulet-courgettes-express',
    name: 'Curry express de poulet et courgettes, riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 110, courgette: 150, 'lait-coco': 50, riz: 60, curry: 2, 'huile-olive': 5 },
    steps: [
      'Cuire le riz.',
      'Dorer le poulet en dés avec le curry, ajouter les courgettes 5 min.',
      'Verser le lait de coco et laisser frémir 5 min.',
    ],
  }),
  defineRecipe({
    id: 'gnocchi-epinards-mozzarella',
    name: 'Gnocchi poêlés aux épinards et mozzarella',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { gnocchi: 180, epinards: 150, mozzarella: 40, ail: 2, 'huile-olive': 5 },
    steps: [
      'Dorer les gnocchi 6 min dans l’huile.',
      "Ajouter l'ail et les épinards jusqu’à ce qu’ils fondent.",
      'Ajouter la mozzarella en morceaux, couvrir 1 min.',
    ],
  }),
  defineRecipe({
    id: 'wok-boeuf-brocoli',
    name: 'Wok de bœuf et brocoli, riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'boeuf-hache': 110, brocoli: 0.4, riz: 60, ail: 2, 'sauce-soja': 15, 'huile-olive': 5 },
    steps: [
      'Cuire le riz et les fleurettes de brocoli 5 min à la vapeur.',
      "Saisir le bœuf avec l'ail 5 min.",
      'Ajouter le brocoli et la sauce soja, mélanger 2 min.',
    ],
  }),
  defineRecipe({
    id: 'omelette-jambon-fromage',
    name: 'Omelette jambon-fromage et salade',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 10,
    ingredients: { oeuf: 3, jambon: 40, emmental: 15, salade: 0.25, 'pain-complet': 40, 'huile-olive': 5 },
    steps: [
      'Battre les œufs, ajouter le jambon en dés.',
      'Cuire 4 min à feu moyen, parsemer d’emmental et plier.',
      'Servir avec la salade et le pain.',
    ],
  }),
  defineRecipe({
    id: 'poulet-haricots-verts-riz',
    name: 'Poulet paprika, haricots verts et riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 120, 'haricots-verts': 150, riz: 60, paprika: 1, 'huile-olive': 5 },
    steps: [
      'Cuire le riz et les haricots verts.',
      'Saisir le poulet saupoudré de paprika, 6 min par face.',
      'Servir ensemble.',
    ],
  }),
  defineRecipe({
    id: 'soupe-legumes-express',
    name: 'Velouté de courgettes et fromage, pain complet',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { courgette: 250, 'pomme-de-terre': 100, bouillon: 0.5, emmental: 25, 'pain-complet': 60 },
    steps: [
      'Couper courgettes et pomme de terre, couvrir d’eau avec le bouillon, cuire 15 min.',
      'Mixer avec l’emmental.',
      'Servir avec le pain grillé.',
    ],
  }),

  // Deuxième série express (20 min maximum) : plus de variété avec dinde, poissons en conserve,
  // légumineuses, céréales et surgelés, tous disponibles toute l'année.
  defineRecipe({
    id: 'poulet-soja-brocoli-riz',
    name: 'Poulet sauté au soja, brocoli et riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 120, 'brocoli-surgele': 150, riz: 60, 'sauce-soja': 15, ail: 2, 'huile-olive': 5 },
    steps: [
      'Cuire le riz. Cuire le brocoli 5 min à l’eau bouillante.',
      "Saisir le poulet en lanières avec l'ail 6 min.",
      'Ajouter le brocoli et la sauce soja, mélanger 2 min.',
    ],
  }),
  defineRecipe({
    id: 'dinde-champignons-penne',
    name: 'Penne à la dinde et aux champignons',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { dinde: 120, champignon: 100, penne: 70, 'creme-epaisse': 20, 'huile-olive': 5 },
    steps: [
      'Cuire les penne.',
      'Dorer la dinde en dés 5 min, ajouter les champignons émincés 5 min.',
      'Ajouter la crème et les pâtes, mélanger.',
    ],
  }),
  defineRecipe({
    id: 'dinde-curry-petits-pois',
    name: 'Dinde au curry, petits pois et riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { dinde: 120, 'petits-pois': 100, riz: 60, 'lait-coco': 40, curry: 2, 'huile-olive': 5 },
    steps: [
      'Cuire le riz.',
      'Dorer la dinde en dés avec le curry, ajouter les petits pois encore surgelés.',
      'Verser le lait de coco, laisser frémir 6 min.',
    ],
  }),
  defineRecipe({
    id: 'spaghetti-boulettes',
    name: 'Spaghetti aux boulettes de bœuf',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { spaghetti: 80, 'boeuf-hache': 100, coulis: 120, herbes: 1, 'huile-olive': 5 },
    steps: [
      'Former de petites boulettes avec le bœuf et les herbes, les dorer 5 min.',
      'Ajouter le coulis, couvrir et mijoter 10 min.',
      'Servir sur les spaghetti cuits.',
    ],
  }),
  defineRecipe({
    id: 'chili-express-mais',
    name: 'Chili express au maïs et riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'boeuf-hache': 100, 'haricots-rouges': 80, 'tomates-concassees': 150, mais: 40, riz: 60, cumin: 1, paprika: 1 },
    steps: [
      'Cuire le riz.',
      'Dorer le bœuf avec les épices, ajouter tomates, haricots et maïs.',
      'Laisser mijoter 10 min et servir sur le riz.',
    ],
  }),
  defineRecipe({
    id: 'dinde-poelee-boulgour',
    name: 'Dinde, poêlée de légumes et boulgour',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { dinde: 120, 'poelee-legumes': 200, boulgour: 60, herbes: 1, 'huile-olive': 5 },
    steps: [
      'Cuire le boulgour 10 min à l’eau bouillante.',
      'Faire sauter la poêlée de légumes 8 min.',
      'Saisir la dinde aux herbes 4 min par face.',
    ],
  }),
  defineRecipe({
    id: 'saucisse-lentilles-carottes',
    name: 'Saucisse, lentilles et carottes',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { saucisse: 110, 'lentilles-boite': 150, carotte: 60, oignon: 30 },
    steps: [
      'Dorer la saucisse 12 min à la poêle.',
      "Faire revenir l'oignon et la carotte en rondelles 5 min.",
      'Ajouter les lentilles rincées, réchauffer 3 min.',
    ],
  }),
  defineRecipe({
    id: 'penne-jambon-petits-pois',
    name: 'Penne au jambon et petits pois',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 15,
    ingredients: { penne: 80, jambon: 50, 'petits-pois': 100, 'creme-epaisse': 20 },
    steps: [
      'Cuire les penne, ajouter les petits pois 4 min avant la fin.',
      'Égoutter, ajouter le jambon en lanières et la crème.',
      'Mélanger et poivrer.',
    ],
  }),
  defineRecipe({
    id: 'poulet-quinoa-poivrons',
    name: 'Poulet, quinoa, poivron et courgette',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 110, quinoa: 60, poivron: 0.5, courgette: 100, paprika: 1, 'huile-olive': 5 },
    steps: [
      'Cuire le quinoa 12 min.',
      'Faire sauter le poivron et la courgette en dés 6 min.',
      'Ajouter le poulet en dés et le paprika, cuire 6 min.',
    ],
  }),
  defineRecipe({
    id: 'poulet-tikka-express',
    name: 'Poulet tikka express et riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 120, 'fromage-blanc': 50, 'tomates-concassees': 100, riz: 60, curry: 2, 'huile-olive': 5 },
    steps: [
      'Cuire le riz.',
      'Dorer le poulet en dés avec le curry, ajouter les tomates 8 min.',
      'Hors du feu, ajouter le fromage blanc.',
    ],
  }),
  defineRecipe({
    id: 'nouilles-boeuf-poivrons',
    name: 'Nouilles sautées au bœuf et poivron',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { nouilles: 70, 'boeuf-hache': 100, poivron: 0.5, oignon: 30, 'sauce-soja': 15, 'huile-olive': 5 },
    steps: [
      'Cuire les nouilles 4 min.',
      "Saisir le bœuf avec l'oignon et le poivron émincés 6 min.",
      'Ajouter les nouilles et la sauce soja.',
    ],
  }),
  defineRecipe({
    id: 'gnocchi-chorizo-tomate',
    name: 'Gnocchi poêlés au chorizo et à la tomate',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 15,
    ingredients: { gnocchi: 180, chorizo: 25, 'tomates-concassees': 120, salade: 0.2 },
    steps: [
      'Dorer le chorizo en dés à sec 2 min, ajouter les gnocchi 5 min.',
      'Verser les tomates, laisser réduire 5 min.',
      'Servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'dinde-moutarde-haricots-verts',
    name: 'Dinde à la moutarde, haricots verts et riz',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { dinde: 130, 'creme-epaisse': 20, 'haricots-verts': 150, riz: 60, moutarde: 10, 'huile-olive': 5 },
    steps: [
      'Cuire le riz et les haricots verts.',
      'Saisir la dinde 4 min par face.',
      'Déglacer avec la crème et la moutarde, laisser épaissir 1 min.',
    ],
  }),

  defineRecipe({
    id: 'saumon-quinoa-epinards',
    name: 'Saumon, quinoa et épinards au citron',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { saumon: 110, quinoa: 60, epinards: 150, citron: 0.25, 'huile-olive': 5 },
    steps: [
      'Cuire le quinoa 12 min.',
      'Saisir le saumon 4 min côté peau puis 2 min.',
      'Faire fondre les épinards, arroser le tout de citron.',
    ],
  }),
  defineRecipe({
    id: 'maquereau-pommes-de-terre',
    name: 'Maquereau à la tomate, pommes de terre et salade',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { maquereau: 120, 'pomme-de-terre': 200, salade: 0.25, vinaigre: 5, 'huile-olive': 5 },
    steps: [
      'Cuire les pommes de terre en morceaux 15 min.',
      'Réchauffer doucement le maquereau dans sa sauce.',
      'Servir avec la salade assaisonnée.',
    ],
  }),
  defineRecipe({
    id: 'colin-petits-pois-semoule',
    name: 'Colin au citron, petits pois et semoule',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { colin: 150, 'petits-pois': 120, semoule: 50, citron: 0.25, 'huile-olive': 5 },
    steps: [
      'Gonfler la semoule. Cuire les petits pois 5 min.',
      'Poêler le colin encore surgelé 6 min par face à couvert.',
      'Arroser de jus de citron.',
    ],
  }),
  defineRecipe({
    id: 'curry-crevettes-coco',
    name: 'Curry de crevettes au lait de coco, riz',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { crevettes: 110, 'lait-coco': 60, poivron: 0.5, riz: 60, curry: 2, 'huile-olive': 5 },
    steps: [
      'Cuire le riz.',
      'Faire revenir le poivron émincé avec le curry 5 min.',
      'Ajouter le lait de coco et les crevettes, chauffer 3 min.',
    ],
  }),
  defineRecipe({
    id: 'penne-saumon-epinards',
    name: 'Penne au saumon et aux épinards',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { penne: 80, saumon: 90, epinards: 100, 'creme-epaisse': 20, citron: 0.2 },
    steps: [
      'Cuire les penne.',
      'Cuire le saumon en dés 4 min, ajouter les épinards jusqu’à ce qu’ils fondent.',
      'Ajouter la crème, le citron et les pâtes.',
    ],
  }),
  defineRecipe({
    id: 'riz-cantonais-crevettes',
    name: 'Riz cantonais aux crevettes',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { riz: 60, crevettes: 80, oeuf: 1, 'petits-pois': 60, 'sauce-soja': 10, 'huile-olive': 5 },
    steps: [
      'Cuire le riz (ou utiliser un reste froid).',
      'Brouiller l’œuf, réserver. Faire sauter les petits pois et les crevettes 3 min.',
      'Ajouter le riz, l’œuf et la sauce soja, mélanger 3 min.',
    ],
  }),
  defineRecipe({
    id: 'poke-bowl-thon',
    name: 'Poke bowl au thon, maïs et carotte',
    category: CATEGORIES.FISH,
    prepMinutes: 15,
    ingredients: { riz: 60, thon: 80, concombre: 0.3, mais: 40, carotte: 50, 'sauce-soja': 10 },
    steps: [
      'Cuire le riz et le laisser tiédir.',
      'Râper la carotte, couper le concombre en dés.',
      'Dresser le tout en bol, arroser de sauce soja.',
    ],
  }),
  defineRecipe({
    id: 'pita-thon-crudites',
    name: 'Pita au thon et crudités',
    category: CATEGORIES.FISH,
    prepMinutes: 10,
    ingredients: { 'pain-pita': 1.5, thon: 70, 'fromage-blanc': 40, carotte: 50, salade: 0.15 },
    steps: [
      'Mélanger le thon et le fromage blanc, poivrer.',
      'Râper la carotte.',
      'Garnir les pitas de salade, carotte et thon.',
    ],
  }),
  defineRecipe({
    id: 'omelette-thon-tomate',
    name: 'Omelette au thon et à la tomate',
    category: CATEGORIES.FISH,
    prepMinutes: 10,
    ingredients: { oeuf: 3, thon: 50, tomate: 100, salade: 0.2, 'pain-complet': 40, 'huile-olive': 5 },
    steps: [
      'Faire revenir la tomate en dés 2 min.',
      'Verser les œufs battus et le thon émietté, cuire 4 min.',
      'Servir avec la salade et le pain.',
    ],
  }),

  defineRecipe({
    id: 'quinoa-legumes-feta',
    name: 'Quinoa aux légumes du soleil et feta',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { quinoa: 60, 'poelee-legumes': 200, feta: 40, herbes: 1, 'huile-olive': 5 },
    steps: [
      'Cuire le quinoa 12 min.',
      'Faire sauter la poêlée de légumes 8 min avec les herbes.',
      'Mélanger et émietter la feta dessus.',
    ],
  }),
  defineRecipe({
    id: 'penne-ricotta-epinards',
    name: 'Penne ricotta et épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { penne: 90, ricotta: 70, epinards: 150, parmesan: 10, ail: 2 },
    steps: [
      'Cuire les penne.',
      "Faire fondre les épinards avec l'ail.",
      'Mélanger pâtes, épinards, ricotta et fromage râpé.',
    ],
  }),
  defineRecipe({
    id: 'omelette-petits-pois-feta',
    name: 'Omelette aux petits pois et feta',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { oeuf: 3, 'petits-pois': 100, feta: 30, salade: 0.25, 'huile-olive': 5 },
    steps: [
      'Cuire les petits pois 4 min, les égoutter.',
      'Verser les œufs battus sur les petits pois, émietter la feta.',
      'Cuire 5 min à feu doux, servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'curry-lentilles-express',
    name: 'Curry express de lentilles et épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { 'lentilles-boite': 180, 'lait-coco': 50, 'tomates-concassees': 100, epinards: 100, riz: 50, curry: 2 },
    steps: [
      'Cuire le riz.',
      'Chauffer les tomates avec le curry, ajouter lentilles rincées et épinards.',
      'Verser le lait de coco, mijoter 5 min.',
    ],
  }),
  defineRecipe({
    id: 'haricots-blancs-oeufs-tomate',
    name: 'Haricots blancs à la tomate et œufs pochés',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { 'haricots-blancs': 150, 'tomates-concassees': 150, oeuf: 2, 'pain-complet': 40, paprika: 1 },
    steps: [
      'Chauffer tomates, haricots rincés et paprika 5 min.',
      'Creuser deux puits, y casser les œufs, couvrir 6 min.',
      'Servir avec le pain grillé.',
    ],
  }),
  defineRecipe({
    id: 'wok-legumes-oeuf-nouilles',
    name: 'Nouilles sautées aux légumes et à l’œuf',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { nouilles: 70, 'poelee-legumes': 200, oeuf: 2, 'sauce-soja': 15, 'huile-olive': 5 },
    steps: [
      'Cuire les nouilles 4 min.',
      'Faire sauter les légumes 6 min, pousser sur le côté et brouiller les œufs.',
      'Ajouter nouilles et sauce soja, mélanger.',
    ],
  }),
  defineRecipe({
    id: 'spaghetti-pesto-petits-pois',
    name: 'Spaghetti au pesto et petits pois',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { spaghetti: 90, pesto: 25, 'petits-pois': 120, parmesan: 10 },
    steps: [
      'Cuire les spaghetti, ajouter les petits pois 4 min avant la fin.',
      'Égoutter en gardant un peu d’eau de cuisson.',
      'Mélanger avec le pesto et le fromage.',
    ],
  }),
  defineRecipe({
    id: 'wrap-oeufs-epinards',
    name: 'Wraps œufs brouillés et épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 10,
    ingredients: { tortilla: 2, oeuf: 2, epinards: 100, emmental: 20, 'huile-olive': 5 },
    steps: [
      'Faire fondre les épinards et bien les égoutter.',
      'Brouiller les œufs avec les épinards et l’emmental.',
      'Garnir les tortillas et rouler.',
    ],
  }),
  defineRecipe({
    id: 'semoule-legumes-pois-chiches',
    name: 'Semoule aux légumes et pois chiches',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { semoule: 60, 'poelee-legumes': 200, 'pois-chiches': 100, cumin: 1, 'huile-olive': 5 },
    steps: [
      'Gonfler la semoule dans son volume d’eau bouillante.',
      'Faire sauter les légumes avec le cumin 8 min, ajouter les pois chiches.',
      'Servir sur la semoule.',
    ],
  }),
  defineRecipe({
    id: 'bowl-houmous-boulgour',
    name: 'Bol boulgour, houmous, crudités et œuf',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { houmous: 50, boulgour: 60, carotte: 80, concombre: 0.3, oeuf: 1 },
    steps: [
      'Cuire le boulgour 10 min et l’œuf 9 min.',
      'Râper la carotte, couper le concombre.',
      'Dresser en bol avec le houmous et l’œuf coupé.',
    ],
  }),
  defineRecipe({
    id: 'penne-brocoli-ail',
    name: 'Penne au brocoli, ail et grana padano',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { penne: 90, 'brocoli-surgele': 150, parmesan: 15, ail: 3, 'huile-olive': 8 },
    steps: [
      'Cuire les penne avec le brocoli les 6 dernières minutes.',
      "Faire dorer l'ail dans l'huile.",
      'Mélanger pâtes, brocoli, ail et fromage.',
    ],
  }),
  defineRecipe({
    id: 'riz-champignons-petits-pois',
    name: 'Riz crémeux aux champignons et petits pois',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { riz: 60, champignon: 100, 'petits-pois': 80, 'creme-epaisse': 25, bouillon: 0.5 },
    steps: [
      'Cuire le riz dans l’eau avec le bouillon.',
      'Faire sauter les champignons 5 min, ajouter les petits pois 4 min.',
      'Mélanger avec le riz et la crème.',
    ],
  }),
  defineRecipe({
    id: 'soupe-haricots-blancs-tomate',
    name: 'Soupe de haricots blancs à la tomate',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { 'haricots-blancs': 150, 'tomates-concassees': 200, carotte: 60, oignon: 30, 'pain-complet': 40, herbes: 1 },
    steps: [
      "Faire revenir l'oignon et la carotte en dés 3 min.",
      'Ajouter tomates, haricots, herbes et 200 ml d’eau, cuire 12 min.',
      'Servir avec le pain grillé.',
    ],
  }),
  defineRecipe({
    id: 'patate-douce-pois-chiches',
    name: 'Poêlée de patate douce, pois chiches et feta',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { 'patate-douce': 200, 'pois-chiches': 100, epinards: 100, feta: 20, cumin: 1, 'huile-olive': 8 },
    steps: [
      'Couper la patate douce en petits dés, la poêler à couvert 12 min.',
      'Ajouter pois chiches, cumin et épinards 4 min.',
      'Émietter la feta dessus.',
    ],
  }),
  defineRecipe({
    id: 'quesadillas-ricotta-epinards',
    name: 'Quesadillas ricotta et épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { tortilla: 2, ricotta: 50, epinards: 100, emmental: 20, salade: 0.15 },
    steps: [
      'Faire fondre les épinards et bien les égoutter.',
      'Étaler ricotta, épinards et emmental sur une tortilla, couvrir de la seconde.',
      'Dorer 3 min par face, servir avec la salade.',
    ],
  }),

  defineRecipe({
    id: 'porridge-banane',
    name: 'Porridge à la banane',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 5,
    ingredients: { 'flocons-avoine': 50, lait: 200, banane: 100 },
    steps: [
      'Chauffer les flocons dans le lait 3 min en remuant (ou 2 min au micro-ondes).',
      'Ajouter la banane en rondelles.',
    ],
  }),
  defineRecipe({
    id: 'fromage-blanc-avoine-pomme',
    name: "Fromage blanc, flocons d'avoine, pomme et amandes",
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 5,
    ingredients: { 'fromage-blanc': 200, 'flocons-avoine': 40, pomme: 150, amandes: 10 },
    steps: [
      'Couper la pomme en dés.',
      'Mélanger avec le fromage blanc, les flocons et les amandes concassées.',
    ],
  }),
  defineRecipe({
    id: 'oeufs-brouilles-pain',
    name: 'Œufs brouillés et pain complet',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 8,
    ingredients: { oeuf: 2, 'pain-complet': 60, beurre: 5 },
    steps: [
      'Battre les œufs et les cuire à feu doux avec le beurre en remuant sans cesse.',
      'Servir avec le pain grillé.',
    ],
  }),
  defineRecipe({
    id: 'tartines-jambon-pomme',
    name: 'Tartines jambon et une pomme',
    category: CATEGORIES.MEAT,
    mealType: MEAL_TYPES.BREAKFAST,
    containsPork: true,
    prepMinutes: 5,
    ingredients: { 'pain-complet': 70, jambon: 40, beurre: 5, pomme: 150 },
    steps: [
      'Faire griller le pain et le beurrer légèrement.',
      'Garnir de jambon. Croquer la pomme à côté.',
    ],
  }),
  defineRecipe({
    id: 'bol-fromage-blanc-banane',
    name: 'Bol fromage blanc, banane et amandes',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 3,
    ingredients: { 'fromage-blanc': 250, banane: 120, amandes: 15 },
    steps: ['Verser le fromage blanc, ajouter la banane en rondelles et les amandes.'],
  }),

  defineRecipe({
    id: 'porridge-pomme',
    name: 'Porridge à la pomme',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 5,
    ingredients: { 'flocons-avoine': 50, lait: 200, pomme: 120 },
    steps: ['Chauffer les flocons dans le lait 3 min.', 'Ajouter la pomme râpée.'],
  }),
  defineRecipe({
    id: 'tartines-oeuf-banane',
    name: 'Tartines, œuf dur et banane',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 10,
    ingredients: { oeuf: 1, 'pain-complet': 60, beurre: 5, banane: 100 },
    steps: ['Cuire l’œuf 9 min (ou la veille).', 'Griller le pain, servir avec la banane.'],
  }),

  defineRecipe({
    id: 'collation-fromage-blanc',
    name: 'Fromage blanc nature',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { 'fromage-blanc': 140 },
    steps: ['Servir frais, nature ou avec une pincée de cannelle. Un pot d’1 kg fait la semaine.'],
  }),
  defineRecipe({
    id: 'collation-fromage-blanc-pomme',
    name: 'Fromage blanc et pomme râpée',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 3,
    ingredients: { 'fromage-blanc': 100, pomme: 80 },
    steps: ['Râper la pomme et la mélanger au fromage blanc.'],
  }),
  defineRecipe({
    id: 'collation-pomme',
    name: 'Une pomme',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { pomme: 150 },
    steps: ['À croquer telle quelle.'],
  }),
  defineRecipe({
    id: 'collation-banane',
    name: 'Une petite banane',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { banane: 100 },
    steps: ['À manger telle quelle.'],
  }),
  defineRecipe({
    id: 'collation-carottes-houmous',
    name: 'Bâtonnets de carotte et houmous',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 3,
    ingredients: { carotte: 100, houmous: 15 },
    steps: ['Couper la carotte en bâtonnets et les tremper dans le houmous.'],
  }),
  defineRecipe({
    id: 'collation-amandes',
    name: 'Une poignée d’amandes',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { amandes: 15 },
    steps: ['Une petite poignée, environ 12 amandes.'],
  }),

  // Ajoutées en octobre 2026 avec les nouveaux produits du catalogue.
  defineRecipe({
    id: 'quenelles-sauce-tomate',
    name: 'Quenelles à la sauce tomate, haricots verts',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { quenelles: 160, coulis: 120, emmental: 15, 'haricots-verts': 150, herbes: 1 },
    steps: [
      'Faire chauffer le coulis avec les herbes, y déposer les quenelles et couvrir 12 min à feu doux : elles gonflent.',
      'Pendant ce temps, cuire les haricots verts 10 min à la poêle avec un fond d’eau.',
      'Parsemer d’emmental, laisser fondre 1 min sous le couvercle et servir.',
    ],
  }),
  defineRecipe({
    id: 'quenelles-champignons-creme',
    name: 'Quenelles à la crème et aux champignons',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { quenelles: 160, 'champignons-boite': 115, 'creme-epaisse': 25, epinards: 150, poivre: 1 },
    steps: [
      'Faire revenir les champignons égouttés 3 min, ajouter la crème et un fond d’eau.',
      'Y poser les quenelles et couvrir 12 min à feu doux.',
      'Cuire les épinards à part 5 min et servir à côté.',
    ],
  }),
  defineRecipe({
    id: 'ravioles-gratinees-epinards',
    name: 'Ravioles à la crème et aux épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { ravioles: 150, epinards: 150, 'creme-epaisse': 20, ail: 3, poivre: 1 },
    steps: [
      'Faire fondre les épinards avec l’ail haché 5 min, ajouter la crème.',
      'Plonger les ravioles 1 à 2 min dans l’eau frémissante, égoutter.',
      'Mélanger délicatement aux épinards et servir aussitôt.',
    ],
  }),
  defineRecipe({
    id: 'ravioles-poelees-mache',
    name: 'Ravioles poêlées et salade de mâche',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 10,
    ingredients: { ravioles: 180, mache: 60, 'huile-olive': 5, vinaigre: 5, moutarde: 3 },
    steps: [
      'Faire dorer les ravioles encore surgelées 3 min par face dans une poêle bien chaude avec un filet d’huile.',
      'Assaisonner la mâche avec la moutarde, le vinaigre et le reste d’huile.',
      'Servir les ravioles croustillantes sur la salade.',
    ],
  }),
  defineRecipe({
    id: 'bouillon-ravioles',
    name: 'Bouillon de ravioles aux légumes',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { ravioles: 150, carotte: 60, poireau: 80, bouillon: 1, persil: 0.2 },
    steps: [
      'Couper la carotte et le poireau en fines rondelles, les cuire 10 min dans 400 ml d’eau avec le bouillon.',
      'Ajouter les ravioles 2 min.',
      'Servir en bol avec le persil ciselé.',
    ],
  }),
  defineRecipe({
    id: 'tortelloni-coulis-courgette',
    name: 'Tortelloni au coulis et à la courgette',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { tortelloni: 150, coulis: 120, courgette: 150, parmesan: 10, herbes: 1, 'huile-olive': 3 },
    steps: [
      'Faire revenir la courgette en dés 6 min dans l’huile, ajouter le coulis et les herbes.',
      'Cuire les tortelloni 3 min, égoutter.',
      'Mélanger à la sauce et parsemer de parmesan.',
    ],
  }),
  defineRecipe({
    id: 'tortelloni-epinards-creme',
    name: 'Tortelloni crème et épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 12,
    ingredients: { tortelloni: 150, epinards: 150, 'creme-epaisse': 20, parmesan: 5, ail: 3 },
    steps: [
      'Faire fondre les épinards avec l’ail 5 min, ajouter la crème.',
      'Cuire les tortelloni 3 min, égoutter et mélanger.',
      'Servir avec le parmesan.',
    ],
  }),
  defineRecipe({
    id: 'poulet-moutarde-rissolees',
    name: 'Poulet à la moutarde, pommes rissolées',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 130, 'pommes-rissolees': 180, 'creme-epaisse': 20, moutarde: 10, 'haricots-verts': 120, 'huile-olive': 3 },
    steps: [
      'Faire dorer les pommes rissolées 15 min à la poêle en remuant de temps en temps.',
      'Dans une autre poêle, saisir le poulet en lanières 6 min avec l’huile, ajouter la crème et la moutarde.',
      'Cuire les haricots verts 10 min avec un fond d’eau et servir le tout ensemble.',
    ],
  }),
  defineRecipe({
    id: 'steak-hache-rissolees',
    name: 'Steak haché, pommes rissolées et haricots verts',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'boeuf-hache': 100, 'pommes-rissolees': 180, 'haricots-verts': 150, 'huile-olive': 3, poivre: 1 },
    steps: [
      'Faire dorer les pommes rissolées 15 min à la poêle.',
      'Cuire les haricots verts 10 min avec un fond d’eau.',
      'Former un steak avec la viande et le cuire 2 à 3 min par face.',
    ],
  }),
  defineRecipe({
    id: 'saumon-rissolees-haricots',
    name: 'Saumon, pommes rissolées et haricots verts',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { saumon: 110, 'pommes-rissolees': 150, 'haricots-verts': 150, citron: 0.25, poivre: 1 },
    steps: [
      'Faire dorer les pommes rissolées 15 min à la poêle.',
      'Cuire les haricots verts 10 min avec un fond d’eau.',
      'Cuire le saumon 4 min côté peau puis 2 min de l’autre côté, arroser de citron.',
    ],
  }),
  defineRecipe({
    id: 'colin-rissolees-petits-pois',
    name: 'Colin au beurre citronné, rissolées et petits pois',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { colin: 140, 'pommes-rissolees': 180, 'petits-pois': 120, beurre: 5, citron: 0.25 },
    steps: [
      'Faire dorer les pommes rissolées 15 min à la poêle.',
      'Cuire les petits pois 6 min dans l’eau bouillante.',
      'Poêler le colin dans le beurre 3 min par face et arroser de citron.',
    ],
  }),
  defineRecipe({
    id: 'saucisses-rissolees-haricots',
    name: 'Saucisses, pommes rissolées et haricots verts',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { saucisse: 80, 'pommes-rissolees': 150, 'haricots-verts': 150, moutarde: 5 },
    steps: [
      'Faire dorer les saucisses 12 min à la poêle à feu moyen en les retournant.',
      'Dans une autre poêle, faire dorer les pommes rissolées 15 min.',
      'Cuire les haricots verts 10 min avec un fond d’eau. Servir avec la moutarde.',
    ],
  }),
  defineRecipe({
    id: 'poelee-rissolees-lardons-oeuf',
    name: 'Poêlée de rissolées, lardons et œuf au plat',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { 'pommes-rissolees': 180, lardons: 40, oeuf: 1, oignon: 40, salade: 0.2, vinaigre: 5 },
    steps: [
      'Faire dorer les pommes rissolées 10 min, ajouter l’oignon émincé et les lardons, poursuivre 5 min.',
      'Cuire l’œuf au plat dans un coin de la poêle.',
      'Servir avec la salade arrosée de vinaigre.',
    ],
  }),
  defineRecipe({
    id: 'omelette-rissolees',
    name: 'Omelette aux pommes rissolées et oignon',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { oeuf: 3, 'pommes-rissolees': 130, oignon: 40, salade: 0.2, herbes: 1, vinaigre: 5 },
    steps: [
      'Faire dorer les pommes rissolées et l’oignon émincé 10 min.',
      'Verser les œufs battus avec les herbes, couvrir et cuire 4 min à feu doux.',
      'Servir avec la salade arrosée de vinaigre.',
    ],
  }),
  defineRecipe({
    id: 'poelee-rissolees-champignons-oeufs',
    name: 'Poêlée campagnarde aux champignons et œufs',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 20,
    ingredients: { 'pommes-rissolees': 180, champignon: 120, oeuf: 2, persil: 0.2, ail: 3 },
    steps: [
      'Faire dorer les pommes rissolées 10 min, ajouter les champignons émincés et l’ail, poursuivre 5 min.',
      'Creuser deux puits, y casser les œufs et couvrir 4 min.',
      'Parsemer de persil ciselé.',
    ],
  }),
  defineRecipe({
    id: 'poulet-pesto-penne',
    name: 'Penne au poulet, pesto et épinards',
    category: CATEGORIES.MEAT,
    prepMinutes: 15,
    ingredients: { 'poulet-filet': 100, penne: 80, pesto: 20, epinards: 120, parmesan: 5 },
    steps: [
      'Cuire les penne 11 min.',
      'Pendant ce temps, saisir le poulet en dés 6 min, ajouter les épinards et les laisser fondre.',
      'Mélanger avec les pâtes et le pesto, parsemer de parmesan.',
    ],
  }),
  defineRecipe({
    id: 'wraps-poulet-fromage-frais',
    name: 'Wraps poulet, carotte et fromage frais',
    category: CATEGORIES.MEAT,
    prepMinutes: 10,
    ingredients: { tortilla: 2, 'blanc-poulet': 80, carotte: 80, 'fromage-frais': 25, salade: 0.15 },
    steps: [
      'Tartiner les tortillas de fromage frais.',
      'Garnir de salade, de carotte râpée et de blanc de poulet.',
      'Rouler serré et couper en deux.',
    ],
  }),
  defineRecipe({
    id: 'quesadillas-poulet-mais',
    name: 'Quesadillas poulet et maïs',
    category: CATEGORIES.MEAT,
    prepMinutes: 15,
    ingredients: { tortilla: 2, 'blanc-poulet': 60, mais: 50, emmental: 25, poivron: 0.33, salade: 0.15 },
    steps: [
      'Garnir une moitié de chaque tortilla de poulet, maïs, poivron en dés et emmental, puis replier.',
      'Dorer 2 à 3 min par face dans une poêle sans matière grasse.',
      'Couper en triangles, servir avec la salade.',
    ],
  }),
  defineRecipe({
    id: 'riz-paella-chorizo',
    name: 'Riz façon paella, chorizo et crevettes',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { riz: 65, chorizo: 25, crevettes: 60, 'petits-pois': 80, poivron: 0.5, oignon: 40, paprika: 1, bouillon: 0.5 },
    steps: [
      'Faire revenir l’oignon, le poivron et le chorizo en rondelles 3 min, ajouter le riz et le paprika.',
      'Mouiller avec 180 ml d’eau et le bouillon, couvrir et cuire 12 min.',
      'Ajouter les petits pois et les crevettes les 4 dernières minutes.',
    ],
  }),
  defineRecipe({
    id: 'endives-jambon-pommes-de-terre',
    name: 'Endives poêlées au jambon et pommes de terre',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { endives: 200, jambon: 50, 'pomme-de-terre': 250, emmental: 20, beurre: 5 },
    steps: [
      'Cuire les pommes de terre en morceaux 15 min à l’eau.',
      'Couper les endives en quatre, les poêler 12 min dans le beurre à couvert.',
      'Ajouter le jambon en lanières et l’emmental, laisser fondre et servir avec les pommes de terre.',
    ],
  }),
  defineRecipe({
    id: 'dinde-miel-soja-riz',
    name: 'Dinde miel-soja, riz et brocoli',
    category: CATEGORIES.MEAT,
    prepMinutes: 15,
    ingredients: { dinde: 130, miel: 10, 'sauce-soja': 15, riz: 70, 'brocoli-surgele': 150, ail: 3 },
    steps: [
      'Cuire le riz 11 min, ajouter le brocoli dans la même eau les 6 dernières minutes.',
      'Saisir la dinde en lanières avec l’ail 5 min.',
      'Ajouter le miel et la sauce soja, laisser caraméliser 1 min et servir.',
    ],
  }),
  defineRecipe({
    id: 'poulet-miel-moutarde-patate-douce',
    name: 'Poulet miel-moutarde et patate douce',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'poulet-filet': 120, miel: 10, moutarde: 10, 'patate-douce': 220, 'haricots-verts': 100, 'huile-olive': 3 },
    steps: [
      'Couper la patate douce en petits cubes et la poêler 15 min à couvert avec l’huile.',
      'Saisir le poulet en dés 6 min, ajouter le miel et la moutarde.',
      'Cuire les haricots verts 10 min avec un fond d’eau et servir.',
    ],
  }),
  defineRecipe({
    id: 'burger-maison',
    name: 'Burger maison et haricots verts',
    category: CATEGORIES.MEAT,
    prepMinutes: 15,
    ingredients: { 'pain-burger': 1, 'boeuf-hache': 100, emmental: 20, salade: 0.1, oignon: 20, 'haricots-verts': 150, moutarde: 5 },
    steps: [
      'Cuire les haricots verts 10 min avec un fond d’eau.',
      'Former un steak et le cuire 2 à 3 min par face, poser l’emmental dessus en fin de cuisson.',
      'Garnir le pain toasté de moutarde, salade, oignon en rondelles et steak.',
    ],
  }),
  defineRecipe({
    id: 'steak-hache-patate-douce',
    name: 'Steak haché et écrasé de patate douce',
    category: CATEGORIES.MEAT,
    prepMinutes: 20,
    ingredients: { 'boeuf-hache': 100, 'patate-douce': 250, 'haricots-verts': 100, beurre: 5, poivre: 1 },
    steps: [
      'Cuire la patate douce en morceaux 15 min à l’eau avec les haricots verts.',
      'Écraser la patate douce avec le beurre.',
      'Cuire le steak 2 à 3 min par face.',
    ],
  }),
  defineRecipe({
    id: 'penne-thon-pesto',
    name: 'Penne au thon et au pesto',
    category: CATEGORIES.FISH,
    prepMinutes: 15,
    ingredients: { penne: 85, thon: 70, pesto: 20, 'haricots-verts': 120 },
    steps: [
      'Cuire les penne 11 min, ajouter les haricots verts dans la même eau les 8 dernières minutes.',
      'Égoutter et mélanger avec le pesto et le thon émietté.',
    ],
  }),
  defineRecipe({
    id: 'spaghetti-sardines-citron',
    name: 'Spaghetti aux sardines, citron et épinards',
    category: CATEGORIES.FISH,
    prepMinutes: 15,
    ingredients: { spaghetti: 85, sardines: 70, citron: 0.5, ail: 3, epinards: 120, persil: 0.2 },
    steps: [
      'Cuire les spaghetti 10 min.',
      'Faire fondre l’ail et les épinards 4 min, ajouter les sardines émiettées avec leur huile.',
      'Mélanger aux pâtes avec le zeste et le jus du citron et le persil.',
    ],
  }),
  defineRecipe({
    id: 'spaghetti-crevettes-epinards',
    name: 'Spaghetti crevettes, ail et épinards',
    category: CATEGORIES.FISH,
    prepMinutes: 15,
    ingredients: { spaghetti: 85, crevettes: 100, epinards: 120, 'creme-epaisse': 20, ail: 5 },
    steps: [
      'Cuire les spaghetti 10 min.',
      'Faire revenir l’ail et les crevettes 3 min, ajouter les épinards puis la crème.',
      'Mélanger avec les pâtes.',
    ],
  }),
  defineRecipe({
    id: 'nouilles-crevettes-pousses',
    name: 'Nouilles sautées, crevettes et pousses de soja',
    category: CATEGORIES.FISH,
    prepMinutes: 15,
    ingredients: { nouilles: 75, crevettes: 100, 'pousses-soja': 90, carotte: 60, oeuf: 1, ail: 3, 'sauce-soja': 15 },
    steps: [
      'Cuire les nouilles 4 min, égoutter.',
      'Faire sauter l’ail, la carotte en bâtonnets et les crevettes 3 min, pousser sur le côté et brouiller l’œuf.',
      'Ajouter les nouilles, les pousses et la sauce soja, sauter 2 min.',
    ],
  }),
  defineRecipe({
    id: 'riz-maquereau-tomate',
    name: 'Riz au maquereau à la tomate et haricots verts',
    category: CATEGORIES.FISH,
    prepMinutes: 15,
    ingredients: { maquereau: 100, riz: 70, 'haricots-verts': 150, citron: 0.25 },
    steps: [
      'Cuire le riz 11 min et les haricots verts 10 min avec un fond d’eau.',
      'Faire chauffer le maquereau dans sa sauce 2 min.',
      'Servir sur le riz avec un trait de citron.',
    ],
  }),
  defineRecipe({
    id: 'salade-pdt-thon-oeuf',
    name: 'Salade tiède pommes de terre, thon, œuf et haricots',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { 'pomme-de-terre': 220, thon: 70, oeuf: 1, 'haricots-verts': 120, 'huile-olive': 6, vinaigre: 5, moutarde: 3 },
    steps: [
      'Cuire les pommes de terre en morceaux 15 min avec l’œuf, ajouter les haricots verts les 10 dernières minutes.',
      'Mélanger la moutarde, le vinaigre et l’huile.',
      'Assembler avec le thon émietté et l’œuf écalé coupé en quatre.',
    ],
  }),
  defineRecipe({
    id: 'colin-curry-coco',
    name: 'Colin au curry et lait de coco, riz',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { colin: 140, 'lait-coco': 70, riz: 65, epinards: 100, oignon: 30, curry: 2 },
    steps: [
      'Cuire le riz 11 min.',
      'Faire revenir l’oignon avec le curry, verser le lait de coco et ajouter les épinards.',
      'Poser le colin en morceaux dans la sauce et couvrir 6 min.',
    ],
  }),
  defineRecipe({
    id: 'bowl-saumon-riz-avocat',
    name: 'Bol de riz au saumon, avocat et concombre',
    category: CATEGORIES.FISH,
    prepMinutes: 20,
    ingredients: { riz: 65, saumon: 100, avocat: 0.25, concombre: 0.3, carotte: 50, 'sauce-soja': 15 },
    steps: [
      'Cuire le riz 11 min.',
      'Cuire le saumon 4 min côté peau puis 2 min de l’autre côté, l’émietter.',
      'Disposer sur le riz avec l’avocat, le concombre et la carotte râpée, arroser de sauce soja.',
    ],
  }),
  defineRecipe({
    id: 'gnocchi-pesto-petits-pois',
    name: 'Gnocchi poêlés au pesto et petits pois',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 12,
    ingredients: { gnocchi: 200, pesto: 20, 'petits-pois': 100, parmesan: 8 },
    steps: [
      'Cuire les petits pois 5 min dans l’eau bouillante, égoutter.',
      'Faire dorer les gnocchi 6 min à la poêle.',
      'Ajouter les petits pois et le pesto, parsemer de parmesan.',
    ],
  }),
  defineRecipe({
    id: 'gnocchi-lardons-haricots',
    name: 'Gnocchi poêlés aux lardons et haricots verts',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 15,
    ingredients: { gnocchi: 200, lardons: 35, 'haricots-verts': 150, oignon: 30 },
    steps: [
      'Cuire les haricots verts 10 min avec un fond d’eau.',
      'Faire dorer les lardons et l’oignon 3 min, ajouter les gnocchi et dorer 6 min.',
      'Ajouter les haricots verts et mélanger.',
    ],
  }),
  defineRecipe({
    id: 'penne-champignons-creme',
    name: 'Penne aux champignons et à la crème',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { penne: 85, champignon: 150, 'creme-epaisse': 30, oignon: 30, parmesan: 8, persil: 0.2 },
    steps: [
      'Cuire les penne 11 min.',
      'Faire revenir l’oignon et les champignons émincés 6 min, ajouter la crème.',
      'Mélanger avec les pâtes, le parmesan et le persil.',
    ],
  }),
  defineRecipe({
    id: 'penne-fromage-frais-epinards',
    name: 'Penne au fromage ail et fines herbes, épinards',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { penne: 85, 'champignons-boite': 115, 'fromage-frais': 30, epinards: 120 },
    steps: [
      'Cuire les penne 11 min.',
      'Faire revenir les champignons égouttés et les épinards 5 min.',
      'Ajouter le fromage frais avec un peu d’eau de cuisson, mélanger avec les pâtes.',
    ],
  }),
  defineRecipe({
    id: 'penne-brocoli-fromage',
    name: 'Penne au brocoli, façon mac & cheese',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { penne: 85, 'brocoli-surgele': 150, lait: 100, emmental: 30, moutarde: 3 },
    steps: [
      'Cuire les penne 11 min avec le brocoli les 6 dernières minutes.',
      'Égoutter, remettre dans la casserole avec le lait, l’emmental et la moutarde.',
      'Remuer 2 min à feu doux jusqu’à ce que la sauce nappe.',
    ],
  }),
  defineRecipe({
    id: 'pita-falafels-houmous',
    name: 'Pita aux falafels et houmous',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 10,
    ingredients: { 'pain-pita': 1, falafels: 80, houmous: 30, concombre: 0.25, carotte: 50, salade: 0.1 },
    steps: [
      'Réchauffer les falafels 5 min à la poêle et le pain pita 1 min.',
      'Tartiner la pita de houmous.',
      'Garnir de salade, de concombre, de carotte râpée et des falafels.',
    ],
  }),
  defineRecipe({
    id: 'bowl-falafels-boulgour',
    name: 'Bol de boulgour, falafels et sauce yaourt',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { boulgour: 55, falafels: 80, concombre: 0.3, carotte: 60, 'yaourt-grec': 40, citron: 0.25, cumin: 1 },
    steps: [
      'Cuire le boulgour 10 min, égoutter.',
      'Réchauffer les falafels 5 min à la poêle.',
      'Mélanger le yaourt avec le citron et le cumin, servir sur le boulgour avec le concombre et la carotte râpée.',
    ],
  }),
  defineRecipe({
    id: 'oeufs-cocotte-epinards',
    name: 'Œufs cocotte aux épinards et mouillettes',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { oeuf: 2, epinards: 150, 'creme-epaisse': 20, emmental: 15, 'pain-complet': 80 },
    steps: [
      'Faire fondre les épinards 4 min à la poêle, ajouter la crème.',
      'Creuser deux puits, casser les œufs, parsemer d’emmental et couvrir 5 min à feu doux.',
      'Servir avec le pain grillé coupé en mouillettes.',
    ],
  }),
  defineRecipe({
    id: 'wok-tofu-nouilles-pousses',
    name: 'Wok de tofu, nouilles et pousses de soja',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { tofu: 120, nouilles: 70, 'pousses-soja': 100, poivron: 0.5, ail: 3, 'sauce-soja': 15 },
    steps: [
      'Cuire les nouilles 4 min, égoutter.',
      'Dorer le tofu en dés 5 min, ajouter l’ail et le poivron émincé 3 min.',
      'Ajouter les nouilles, les pousses et la sauce soja, sauter 2 min.',
    ],
  }),
  defineRecipe({
    id: 'wok-dinde-pousses-nouilles',
    name: 'Wok de dinde, nouilles et pousses de soja',
    category: CATEGORIES.MEAT,
    prepMinutes: 15,
    ingredients: { dinde: 120, nouilles: 70, 'pousses-soja': 100, carotte: 60, ail: 3, 'sauce-soja': 15 },
    steps: [
      'Cuire les nouilles 4 min, égoutter.',
      'Saisir la dinde en lanières avec l’ail et la carotte en bâtonnets 5 min.',
      'Ajouter les nouilles, les pousses et la sauce soja, sauter 2 min.',
    ],
  }),
  defineRecipe({
    id: 'bowl-mexicain-haricots-mais',
    name: 'Bol mexicain riz, haricots rouges et maïs',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { riz: 60, 'haricots-rouges': 100, mais: 60, avocat: 0.25, poivron: 0.5, 'yaourt-grec': 30, cumin: 1 },
    steps: [
      'Cuire le riz 11 min.',
      'Réchauffer les haricots rincés et le maïs avec le poivron en dés et le cumin 4 min.',
      'Servir sur le riz avec l’avocat en tranches et une cuillère de yaourt.',
    ],
  }),
  defineRecipe({
    id: 'croque-monsieur-salade',
    name: 'Croque-monsieur et salade verte',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 12,
    ingredients: { 'pain-complet': 100, jambon: 40, emmental: 30, beurre: 5, salade: 0.2, vinaigre: 5 },
    steps: [
      'Garnir deux tranches de pain de jambon et d’emmental, refermer et beurrer l’extérieur.',
      'Dorer 3 min par face à la poêle, couvercle posé pour faire fondre le fromage.',
      'Servir avec la salade arrosée de vinaigre.',
    ],
  }),
  defineRecipe({
    id: 'poulet-artichauts-semoule',
    name: 'Poulet citronné aux artichauts, semoule',
    category: CATEGORIES.MEAT,
    prepMinutes: 15,
    ingredients: { 'poulet-filet': 120, artichauts: 120, semoule: 65, citron: 0.5, oignon: 30, 'huile-olive': 3, herbes: 1 },
    steps: [
      'Verser l’eau bouillante sur la semoule, couvrir 5 min.',
      'Saisir le poulet en dés et l’oignon 6 min, ajouter les artichauts égouttés et les herbes 3 min.',
      'Arroser de jus de citron et servir sur la semoule.',
    ],
  }),
  defineRecipe({
    id: 'taboule-poulet-concombre',
    name: 'Taboulé de boulgour au poulet et concombre',
    category: CATEGORIES.MEAT,
    prepMinutes: 15,
    ingredients: { boulgour: 65, 'poulet-filet': 110, concombre: 0.3, citron: 0.5, persil: 0.3, 'huile-olive': 6 },
    steps: [
      'Cuire le boulgour 10 min, égoutter et rafraîchir.',
      'Saisir le poulet en dés 6 min.',
      'Mélanger avec le concombre en dés, le persil, le citron et l’huile.',
    ],
  }),
  defineRecipe({
    id: 'salade-lentilles-betteraves-feta',
    name: 'Salade de lentilles, betteraves et feta',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 10,
    ingredients: { 'lentilles-boite': 200, betteraves: 120, feta: 40, mache: 50, 'huile-olive': 6, vinaigre: 5, moutarde: 3 },
    steps: [
      'Rincer et égoutter les lentilles.',
      'Couper les betteraves en dés et émietter la feta.',
      'Mélanger avec la mâche et la vinaigrette moutardée.',
    ],
  }),
  defineRecipe({
    id: 'salade-quinoa-betteraves-chevre',
    name: 'Salade de quinoa, betteraves et chèvre',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 15,
    ingredients: { quinoa: 65, betteraves: 120, chevre: 40, mache: 50, 'huile-olive': 5, vinaigre: 5 },
    steps: [
      'Cuire le quinoa 12 min, égoutter.',
      'Couper les betteraves en dés et le chèvre en morceaux.',
      'Mélanger avec la mâche, l’huile et le vinaigre.',
    ],
  }),
  defineRecipe({
    id: 'salade-endives-chevre-pomme',
    name: 'Salade d’endives, chèvre chaud et pomme',
    category: CATEGORIES.VEGETARIAN,
    prepMinutes: 10,
    ingredients: { endives: 200, chevre: 50, pomme: 100, 'pain-complet': 70, miel: 5, 'huile-olive': 5, vinaigre: 5 },
    steps: [
      'Poser le chèvre sur le pain, arroser de miel et passer 4 min sous le gril du four.',
      'Émincer les endives et la pomme, assaisonner d’huile et de vinaigre.',
      'Servir les tartines chaudes sur la salade.',
    ],
  }),
  defineRecipe({
    id: 'salade-poulet-mache-betteraves',
    name: 'Salade de mâche, poulet, betteraves et œuf',
    category: CATEGORIES.MEAT,
    prepMinutes: 12,
    ingredients: { 'blanc-poulet': 100, mache: 60, betteraves: 100, mais: 60, oeuf: 1, 'pain-complet': 50, 'huile-olive': 5, vinaigre: 5 },
    steps: [
      'Cuire l’œuf 9 min, le rafraîchir.',
      'Couper les betteraves en dés et le poulet en lanières.',
      'Mélanger avec la mâche, le maïs et la vinaigrette, servir avec l’œuf et le pain.',
    ],
  }),
  defineRecipe({
    id: 'salade-tiede-pdt-lardons',
    name: 'Salade tiède pommes de terre, lardons et haricots',
    category: CATEGORIES.MEAT,
    containsPork: true,
    prepMinutes: 20,
    ingredients: { 'pomme-de-terre': 220, 'haricots-verts': 150, lardons: 40, oeuf: 1, vinaigre: 8, moutarde: 3 },
    steps: [
      'Cuire les pommes de terre en morceaux 15 min avec l’œuf, ajouter les haricots verts les 10 dernières minutes.',
      'Faire dorer les lardons 4 min à sec.',
      'Mélanger le tout avec le vinaigre et la moutarde, l’œuf écalé coupé en quatre.',
    ],
  }),

  defineRecipe({
    id: 'bol-yaourt-grec-avoine-banane',
    name: 'Yaourt grec, flocons d’avoine et banane',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 3,
    ingredients: { 'yaourt-grec': 150, 'flocons-avoine': 30, banane: 100 },
    steps: ['Verser le yaourt, ajouter les flocons et la banane en rondelles.'],
  }),
  defineRecipe({
    id: 'tartines-cacahuete-banane',
    name: 'Tartines beurre de cacahuète et banane',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 5,
    ingredients: { 'pain-complet': 70, 'beurre-cacahuete': 20, banane: 100 },
    steps: ['Griller le pain, le tartiner de beurre de cacahuète.', 'Couvrir de rondelles de banane.'],
  }),
  defineRecipe({
    id: 'oeufs-jambon-pain',
    name: 'Œufs au plat, jambon et pain grillé',
    category: CATEGORIES.MEAT,
    mealType: MEAL_TYPES.BREAKFAST,
    containsPork: true,
    prepMinutes: 7,
    ingredients: { oeuf: 2, jambon: 40, 'pain-complet': 60, 'huile-olive': 3 },
    steps: ['Cuire les œufs au plat 3 min dans l’huile, réchauffer le jambon à côté.', 'Servir avec le pain grillé.'],
  }),
  defineRecipe({
    id: 'porridge-cacahuete',
    name: 'Porridge au beurre de cacahuète',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 5,
    ingredients: { 'flocons-avoine': 50, lait: 200, 'beurre-cacahuete': 15 },
    steps: ['Chauffer les flocons dans le lait 3 min en remuant.', 'Ajouter le beurre de cacahuète et mélanger.'],
  }),
  defineRecipe({
    id: 'bifidus-avoine-pomme',
    name: 'Bifidus, flocons d’avoine, pomme et miel',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 3,
    ingredients: { bifidus: 200, 'flocons-avoine': 40, pomme: 120, miel: 5 },
    steps: ['Verser le bifidus, ajouter les flocons et la pomme en dés.', 'Napper de miel.'],
  }),
  defineRecipe({
    id: 'galettes-fromage-blanc-miel',
    name: 'Galettes de maïs, fromage blanc au miel et banane',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 3,
    ingredients: { 'galettes-mais': 30, 'fromage-blanc': 150, miel: 10, banane: 100 },
    steps: ['Mélanger le fromage blanc et le miel.', 'Servir avec les galettes et la banane.'],
  }),
  defineRecipe({
    id: 'tartines-fromage-frais-oeuf',
    name: 'Tartines au fromage frais, œuf dur et concombre',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 10,
    ingredients: { 'pain-complet': 70, 'fromage-frais': 25, oeuf: 1, concombre: 0.25 },
    steps: ['Cuire l’œuf 9 min (ou la veille).', 'Tartiner le pain de fromage frais, garnir de concombre et d’œuf en tranches.'],
  }),
  defineRecipe({
    id: 'pancakes-banane-avoine',
    name: 'Pancakes banane et avoine',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 12,
    ingredients: { banane: 100, oeuf: 2, 'flocons-avoine': 40, 'huile-olive': 3 },
    steps: [
      'Écraser la banane, mélanger avec les œufs et les flocons.',
      'Cuire de petits pancakes 2 min par face dans une poêle huilée.',
    ],
  }),
  defineRecipe({
    id: 'pain-perdu-express',
    name: 'Pain perdu express au miel',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 10,
    ingredients: { 'pain-complet': 70, oeuf: 1, lait: 80, beurre: 5, miel: 10 },
    steps: [
      'Battre l’œuf avec le lait, y tremper les tranches de pain.',
      'Dorer 2 min par face dans le beurre et napper de miel.',
    ],
  }),
  defineRecipe({
    id: 'fromage-blanc-compote-avoine',
    name: 'Fromage blanc, compote et flocons d’avoine',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.BREAKFAST,
    prepMinutes: 2,
    ingredients: { 'fromage-blanc': 200, compote: 100, 'flocons-avoine': 35 },
    steps: ['Verser le fromage blanc, ajouter la compote et les flocons.'],
  }),

  defineRecipe({
    id: 'collation-yaourt-grec-miel',
    name: 'Yaourt grec au miel',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { 'yaourt-grec': 50, miel: 5 },
    steps: ['Deux cuillères de yaourt, un filet de miel.'],
  }),
  defineRecipe({
    id: 'collation-bifidus',
    name: 'Un bifidus nature',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { bifidus: 125 },
    steps: ['Servir frais, un pot d’environ 125 g.'],
  }),
  defineRecipe({
    id: 'collation-galettes-cacahuete',
    name: 'Galettes de maïs au beurre de cacahuète',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { 'galettes-mais': 15, 'beurre-cacahuete': 5 },
    steps: ['Deux galettes, une fine couche de beurre de cacahuète.'],
  }),
  defineRecipe({
    id: 'collation-compote',
    name: 'Une compote de pomme',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { compote: 150 },
    steps: ['Un petit bol, frais ou tiédi.'],
  }),
  defineRecipe({
    id: 'collation-oeuf-dur',
    name: 'Un œuf dur',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 10,
    ingredients: { oeuf: 1 },
    steps: ['Cuire l’œuf 9 min, le rafraîchir. Se garde 4 jours au frigo.'],
  }),
  defineRecipe({
    id: 'collation-poulet-concombre',
    name: 'Blanc de poulet et concombre',
    category: CATEGORIES.MEAT,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 2,
    ingredients: { 'blanc-poulet': 40, concombre: 0.25 },
    steps: ['Rouler le poulet autour de bâtonnets de concombre.'],
  }),
  defineRecipe({
    id: 'collation-concombre-houmous',
    name: 'Concombre et houmous',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 2,
    ingredients: { concombre: 0.25, houmous: 15 },
    steps: ['Couper le concombre en bâtonnets et les tremper dans le houmous.'],
  }),
  defineRecipe({
    id: 'collation-banane-cacahuete',
    name: 'Demi-banane au beurre de cacahuète',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { banane: 60, 'beurre-cacahuete': 5 },
    steps: ['Une demi-banane en rondelles avec une pointe de beurre de cacahuète.'],
  }),
  defineRecipe({
    id: 'collation-fromage-blanc-miel',
    name: 'Fromage blanc au miel',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 1,
    ingredients: { 'fromage-blanc': 120, miel: 5 },
    steps: ['Un filet de miel sur le fromage blanc.'],
  }),
  defineRecipe({
    id: 'collation-galettes-jambon',
    name: 'Galettes de maïs et jambon',
    category: CATEGORIES.MEAT,
    mealType: MEAL_TYPES.SNACK,
    containsPork: true,
    prepMinutes: 1,
    ingredients: { 'galettes-mais': 15, jambon: 20 },
    steps: ['Deux galettes avec une demi-tranche de jambon.'],
  }),
  defineRecipe({
    id: 'collation-endive-fromage-frais',
    name: 'Feuilles d’endive au fromage frais',
    category: CATEGORIES.VEGETARIAN,
    mealType: MEAL_TYPES.SNACK,
    prepMinutes: 2,
    ingredients: { endives: 60, 'fromage-frais': 15 },
    steps: ['Garnir quelques feuilles d’endive d’une noisette de fromage frais.'],
  }),
]);

export const RECIPES_BY_ID = new Map(RECIPES.map((recipe) => [recipe.id, recipe]));

export function countFreshIngredients(recipe) {
  return Object.keys(recipe.ingredients).filter((productId) => !PRODUCTS_BY_ID.get(productId)?.isPantryStaple).length;
}

export function fitsTimeLimit(recipe, maxPrepMinutes) {
  if (maxPrepMinutes <= 0) {
    return true;
  }
  return recipe.prepMinutes <= maxPrepMinutes
    && countFreshIngredients(recipe) <= MAX_FRESH_INGREDIENTS_WHEN_TIME_LIMITED;
}
